---
# Publish motherstarter to pypi based on a new release
name: Publish

on:  # yamllint disable rule:truthy
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.9
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.9
      - name: setup publish env
        run: |
            python -m pip install --upgrade pip
            python -m pip install setuptools
            python -m pip install wheel
            python -m pip install twine
      - name: build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_UNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PWORD }}
        run: |
          python setup.py sdist bdist_wheel
          python -m twine upload dist/*
